import { ProgressStepper } from "@/components/ProgressStepper";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Download, CheckCircle2, FileText, DollarSign, Cpu, Search } from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";

export default function FinalResponse() {
  const location = useLocation();
  const navigate = useNavigate();
  const { selectedSKU, rfpRequirements, pricingData } = location.state || {
    selectedSKU: "AP-XLPE-95A",
    rfpRequirements: {
      item: "1100V, 3C 95 sqmm Aluminium Cable",
      quantity: "1200 meters",
    },
    pricingData: {
      grandTotal: 513500,
    },
  };

  const handleDownloadPDF = () => {
    // Create a simple text representation of the RFP response
    const rfpContent = `
RFP RESPONSE - AUTOMATED GENERATION
=====================================

SALES AGENT SUMMARY
-------------------
RFP detected and qualified for automated response processing.
Client Requirements: ${rfpRequirements.item}
Quantity: ${rfpRequirements.quantity}

TECHNICAL AGENT - SKU MATCH RESULT
----------------------------------
Selected SKU: ${selectedSKU}
Match Percentage: 100%
Reason: All RFP specifications matched perfectly
Status: ✓ Approved for procurement

PRICING AGENT - COST BREAKDOWN
-------------------------------
Material Cost: ₹${pricingData.materialCost?.toLocaleString() || "504,000"}
Test Costs: ₹${pricingData.testCosts?.toLocaleString() || "9,500"}
Grand Total: ₹${pricingData.grandTotal.toLocaleString()}

RECOMMENDATION
--------------
We recommend proceeding with SKU ${selectedSKU} which meets all RFP requirements 
with 100% specification match and competitive pricing.

Generated by OrbitronFlow AI-Powered RFP Automation System
    `.trim();

    // Create blob and download
    const blob = new Blob([rfpContent], { type: "text/plain" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `RFP_Response_${selectedSKU}_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-background">
      <ProgressStepper />

      <div className="container mx-auto px-4 py-8">
        {/* Page Header */}
        <div className="text-center mb-8 animate-fade-in-up">
          <Badge className="bg-status-complete/10 text-status-complete border-status-complete/20 mb-4">
            <CheckCircle2 className="w-3 h-3 mr-1" />
            Response Ready
          </Badge>
          <h1 className="text-4xl font-bold gradient-text mb-2">
            Final RFP Response Generation
          </h1>
          <p className="text-muted-foreground">
            Complete automated response generated by AI agents
          </p>
        </div>

        {/* Agent Summary Cards */}
        <div className="grid md:grid-cols-3 gap-6 mb-8">
          {/* Sales Agent Summary */}
          <Card className="animate-fade-in-up stagger-1 border-agent-sales/30">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <Search className="w-5 h-5 text-agent-sales" />
                Sales Agent
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <p className="text-sm text-muted-foreground">
                RFP detected and qualified for automated response processing
              </p>
              <div className="pt-2 space-y-1">
                <p className="text-xs text-muted-foreground">Requirements</p>
                <p className="font-semibold text-sm">{rfpRequirements.item}</p>
                <p className="text-xs text-agent-sales">Qty: {rfpRequirements.quantity}</p>
              </div>
            </CardContent>
          </Card>

          {/* Technical Agent Summary */}
          <Card className="animate-fade-in-up stagger-2 border-agent-technical/30">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <Cpu className="w-5 h-5 text-agent-technical" />
                Technical Agent
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <p className="text-sm text-muted-foreground">
                SKU matched with 100% specification accuracy
              </p>
              <div className="pt-2 space-y-1">
                <p className="text-xs text-muted-foreground">Selected SKU</p>
                <p className="font-bold text-lg text-agent-technical">{selectedSKU}</p>
                <Badge className="bg-status-complete text-white">100% Match</Badge>
              </div>
            </CardContent>
          </Card>

          {/* Pricing Agent Summary */}
          <Card className="animate-fade-in-up stagger-3 border-agent-pricing/30">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <DollarSign className="w-5 h-5 text-agent-pricing" />
                Pricing Agent
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <p className="text-sm text-muted-foreground">
                Complete cost breakdown calculated
              </p>
              <div className="pt-2 space-y-1">
                <p className="text-xs text-muted-foreground">Grand Total</p>
                <p className="font-bold text-2xl text-agent-pricing">
                  ₹{pricingData.grandTotal.toLocaleString()}
                </p>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Final Response Document */}
        <Card className="mb-8 animate-fade-in-up stagger-4 border-2 border-primary/50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileText className="w-6 h-6 text-primary" />
              Generated RFP Response
            </CardTitle>
            <CardDescription>
              Complete response generated by orchestrating multiple AI agents
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Sales Agent Section */}
            <div className="space-y-2">
              <h3 className="font-semibold text-agent-sales flex items-center gap-2">
                <Search className="w-4 h-4" />
                Sales Agent Summary
              </h3>
              <p className="text-muted-foreground">
                RFP detected and qualified for automated response processing. Client requirements
                for {rfpRequirements.item} with quantity of {rfpRequirements.quantity} has been
                analyzed and approved for response generation.
              </p>
            </div>

            {/* Technical Agent Section */}
            <div className="space-y-2">
              <h3 className="font-semibold text-agent-technical flex items-center gap-2">
                <Cpu className="w-4 h-4" />
                Technical Agent - SKU Match Result
              </h3>
              <div className="bg-agent-technical/5 p-4 rounded-lg border border-agent-technical/20">
                <div className="grid md:grid-cols-3 gap-4">
                  <div>
                    <p className="text-sm text-muted-foreground">Selected SKU</p>
                    <p className="font-bold text-lg">{selectedSKU}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Match Percentage</p>
                    <p className="font-bold text-lg text-status-complete">100%</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Status</p>
                    <Badge className="bg-status-complete text-white">
                      <CheckCircle2 className="w-3 h-3 mr-1" />
                      Approved
                    </Badge>
                  </div>
                </div>
                <p className="text-sm text-muted-foreground mt-3">
                  All RFP specifications matched perfectly. This product meets all technical
                  requirements including voltage, material, insulation type, and industry standards.
                </p>
              </div>
            </div>

            {/* Pricing Agent Section */}
            <div className="space-y-2">
              <h3 className="font-semibold text-agent-pricing flex items-center gap-2">
                <DollarSign className="w-4 h-4" />
                Pricing Agent - Cost Breakdown
              </h3>
              <div className="bg-agent-pricing/5 p-4 rounded-lg border border-agent-pricing/20">
                <div className="space-y-3">
                  <div className="flex justify-between items-center">
                    <span className="text-muted-foreground">Material Cost</span>
                    <span className="font-semibold">
                      ₹{pricingData.materialCost?.toLocaleString() || "504,000"}
                    </span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-muted-foreground">Test Costs</span>
                    <span className="font-semibold">
                      ₹{pricingData.testCosts?.toLocaleString() || "9,500"}
                    </span>
                  </div>
                  <div className="border-t border-border pt-3 flex justify-between items-center">
                    <span className="font-bold">Grand Total</span>
                    <span className="text-2xl font-bold text-agent-pricing">
                      ₹{pricingData.grandTotal.toLocaleString()}
                    </span>
                  </div>
                </div>
              </div>
            </div>

            {/* Recommendation */}
            <div className="bg-gradient-to-br from-primary/5 to-accent/5 p-6 rounded-lg border-2 border-primary/20">
              <h3 className="font-bold text-lg mb-2">Recommendation</h3>
              <p className="text-muted-foreground">
                Based on the comprehensive analysis by our AI agents, we recommend proceeding with
                SKU <span className="font-semibold text-foreground">{selectedSKU}</span> which
                meets all RFP requirements with 100% specification match and competitive pricing of{" "}
                <span className="font-semibold text-foreground">
                  ₹{pricingData.grandTotal.toLocaleString()}
                </span>
                . This solution ensures compliance with all technical standards while providing
                optimal value.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row justify-between items-center gap-4 animate-fade-in-up stagger-5">
          <Button variant="outline" size="lg" onClick={() => navigate("/")}>
            Process New RFP
          </Button>
          <Button size="lg" onClick={handleDownloadPDF} className="gap-2">
            <Download className="w-5 h-5" />
            Download Final RFP Response
          </Button>
        </div>
      </div>
    </div>
  );
}
