import { ProgressStepper } from "@/components/ProgressStepper";
import { AgentStatus } from "@/components/AgentStatus";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Download, CheckCircle2, FileText, DollarSign, Cpu, Search, Send } from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useToast } from "@/hooks/use-toast";

export default function FinalResponse() {
  const location = useLocation();
  const navigate = useNavigate();
  const { toast } = useToast();
  const { selectedSKU, rfpRequirements, pricingData } = location.state || {
    selectedSKU: "AP-XLPE-95A",
    rfpRequirements: {
      item: "1100V, 3C 95 sqmm Aluminium Cable",
      quantity: "1200 meters",
    },
    pricingData: {
      grandTotal: 513500,
    },
  };

  const handleDownloadPDF = () => {
    // Create a simple text representation of the RFP response
    const rfpContent = `
RFP RESPONSE - AUTOMATED GENERATION
=====================================

MAIN AGENT - WORKFLOW ORCHESTRATION
------------------------------------
✓ Workflow initiated and agents coordinated
✓ All agent outputs validated and synthesized
✓ Quality checks passed - Ready for submission

SALES AGENT SUMMARY
-------------------
RFP detected and qualified for automated response processing.
Client Requirements: ${rfpRequirements.item}
Quantity: ${rfpRequirements.quantity}

TECHNICAL AGENT - SKU MATCH RESULT
----------------------------------
Selected SKU: ${selectedSKU}
Match Percentage: 100%
Reason: All RFP specifications matched perfectly
Status: ✓ Approved for procurement

PRICING AGENT - COST BREAKDOWN
-------------------------------
Material Cost: ₹${pricingData.materialCost?.toLocaleString() || "504,000"}
Test Costs: ₹${pricingData.testCosts?.toLocaleString() || "9,500"}
Grand Total: ₹${pricingData.grandTotal.toLocaleString()}

MAIN AGENT - FINAL RECOMMENDATION
----------------------------------
We recommend proceeding with SKU ${selectedSKU} which meets all RFP requirements 
with 100% specification match and competitive pricing.

Generated by OrbitronFlow AI-Powered RFP Automation System
    `.trim();

    // Create blob and download
    const blob = new Blob([rfpContent], { type: "text/plain" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `RFP_Response_${selectedSKU}_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
    
    toast({
      title: "Success!",
      description: "RFP response downloaded successfully.",
    });
  };

  const handleSubmitResponse = () => {
    toast({
      title: "RFP Response Submitted!",
      description: "Your response has been submitted successfully.",
    });
  };

  return (
    <div className="min-h-screen bg-background">
      <ProgressStepper />
      <AgentStatus />

      <div className="container mx-auto px-4 py-8">
        {/* Success Message */}
        <div className="text-center mb-8 animate-fade-in-up">
          <div className="bg-status-complete/10 border-2 border-status-complete/30 rounded-lg p-6 mb-6">
            <CheckCircle2 className="w-16 h-16 text-status-complete mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-status-complete mb-2">
              RFP Response Ready!
            </h2>
            <p className="text-muted-foreground text-lg mb-2">
              Main Agent has validated all outputs and compiled the final response.
            </p>
            <Badge className="bg-agent-orchestrator text-white">
              Main Agent: Quality Check Complete ✓
            </Badge>
          </div>
          <h1 className="text-4xl font-bold gradient-text mb-2">
            Final RFP Response
          </h1>
          <p className="text-muted-foreground">
            Complete automated response generated by AI agents
          </p>
        </div>

        {/* Agent Summary Cards */}
        <div className="grid md:grid-cols-3 gap-6 mb-8">
          {/* Sales Agent Summary */}
          <Card className="animate-fade-in-up stagger-1 border-agent-sales/30">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <Search className="w-5 h-5 text-agent-sales" />
                Sales Agent
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <p className="text-sm text-muted-foreground">
                RFP detected and qualified for automated response processing
              </p>
              <div className="pt-2 space-y-1">
                <p className="text-xs text-muted-foreground">Requirements</p>
                <p className="font-semibold text-sm">{rfpRequirements.item}</p>
                <p className="text-xs text-agent-sales">Qty: {rfpRequirements.quantity}</p>
              </div>
            </CardContent>
          </Card>

          {/* Technical Agent Summary */}
          <Card className="animate-fade-in-up stagger-2 border-agent-technical/30">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <Cpu className="w-5 h-5 text-agent-technical" />
                Technical Agent
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <p className="text-sm text-muted-foreground">
                SKU matched with 100% specification accuracy
              </p>
              <div className="pt-2 space-y-1">
                <p className="text-xs text-muted-foreground">Selected SKU</p>
                <p className="font-bold text-lg text-agent-technical">{selectedSKU}</p>
                <Badge className="bg-status-complete text-white">100% Match</Badge>
              </div>
            </CardContent>
          </Card>

          {/* Pricing Agent Summary */}
          <Card className="animate-fade-in-up stagger-3 border-agent-pricing/30">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <DollarSign className="w-5 h-5 text-agent-pricing" />
                Pricing Agent
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <p className="text-sm text-muted-foreground">
                Complete cost breakdown calculated
              </p>
              <div className="pt-2 space-y-1">
                <p className="text-xs text-muted-foreground">Grand Total</p>
                <p className="font-bold text-2xl text-agent-pricing">
                  ₹{pricingData.grandTotal.toLocaleString()}
                </p>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Response Summary */}
        <Card className="mb-8 animate-fade-in-up stagger-4 border-2 border-primary/50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileText className="w-6 h-6 text-primary" />
              Response Summary
            </CardTitle>
            <CardDescription>
              Complete response generated by orchestrating multiple AI agents
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Overall Confidence Score */}
            <div className="bg-gradient-to-br from-status-complete/10 to-primary/10 p-6 rounded-lg border-2 border-status-complete/30">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Overall Confidence Score</p>
                  <p className="text-5xl font-bold text-status-complete">92%</p>
                </div>
                <CheckCircle2 className="w-16 h-16 text-status-complete" />
              </div>
              <p className="text-sm text-muted-foreground mt-4">
                High confidence based on 100% spec match, competitive pricing, and full compliance
              </p>
            </div>

            {/* Selected Products Table */}
            <div className="space-y-3">
              <h3 className="font-semibold text-lg flex items-center gap-2">
                <Cpu className="w-5 h-5 text-agent-technical" />
                Selected Products
              </h3>
              
              {/* Desktop Table View */}
              <div className="hidden md:block overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>SKU</TableHead>
                      <TableHead>Description</TableHead>
                      <TableHead className="text-right">Match %</TableHead>
                      <TableHead className="text-right">Quantity</TableHead>
                      <TableHead className="text-right">Total Cost</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-bold">{selectedSKU}</TableCell>
                      <TableCell>{rfpRequirements.item}</TableCell>
                      <TableCell className="text-right">
                        <Badge className="bg-status-complete text-white">100%</Badge>
                      </TableCell>
                      <TableCell className="text-right">{rfpRequirements.quantity}</TableCell>
                      <TableCell className="text-right font-bold text-agent-pricing">
                        ₹{pricingData.materialCost?.toLocaleString() || "504,000"}
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>

              {/* Mobile Card View */}
              <div className="md:hidden border rounded-lg p-4 space-y-3 bg-card">
                <div className="flex justify-between items-start">
                  <h4 className="font-bold text-lg">{selectedSKU}</h4>
                  <Badge className="bg-status-complete text-white">100%</Badge>
                </div>
                <p className="text-sm">{rfpRequirements.item}</p>
                <div className="space-y-2 pt-2 border-t">
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-muted-foreground">Quantity</span>
                    <span className="font-semibold">{rfpRequirements.quantity}</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-muted-foreground">Total Cost</span>
                    <span className="font-bold text-lg text-agent-pricing">
                      ₹{pricingData.materialCost?.toLocaleString() || "504,000"}
                    </span>
                  </div>
                </div>
              </div>
            </div>

            {/* Pricing Breakdown */}
            <div className="space-y-3">
              <h3 className="font-semibold text-lg flex items-center gap-2">
                <DollarSign className="w-5 h-5 text-agent-pricing" />
                Pricing Breakdown
              </h3>
              <div className="bg-agent-pricing/5 p-5 rounded-lg border border-agent-pricing/20">
                <div className="space-y-3">
                  <div className="flex justify-between items-center pb-2 border-b border-border">
                    <span className="text-muted-foreground">Material Cost</span>
                    <span className="font-semibold text-lg">
                      ₹{pricingData.materialCost?.toLocaleString() || "504,000"}
                    </span>
                  </div>
                  <div className="flex justify-between items-center pb-2 border-b border-border">
                    <span className="text-muted-foreground">Testing Cost</span>
                    <span className="font-semibold text-lg">
                      ₹{pricingData.testCosts?.toLocaleString() || "9,500"}
                    </span>
                  </div>
                  <div className="flex justify-between items-center pt-2">
                    <span className="font-bold text-lg">Grand Total</span>
                    <span className="text-3xl font-bold text-agent-pricing">
                      ₹{pricingData.grandTotal.toLocaleString()}
                    </span>
                  </div>
                </div>
              </div>
            </div>

            {/* Testing Compliance Status */}
            <div className="space-y-3">
              <h3 className="font-semibold text-lg flex items-center gap-2">
                <CheckCircle2 className="w-5 h-5 text-status-complete" />
                Testing Compliance Status
              </h3>
              <div className="grid md:grid-cols-3 gap-4">
                <div className="bg-status-complete/10 p-4 rounded-lg border border-status-complete/20">
                  <CheckCircle2 className="w-6 h-6 text-status-complete mb-2" />
                  <p className="font-semibold mb-1">Tensile Test</p>
                  <p className="text-sm text-muted-foreground">Compliant - ₹3,000</p>
                </div>
                <div className="bg-status-complete/10 p-4 rounded-lg border border-status-complete/20">
                  <CheckCircle2 className="w-6 h-6 text-status-complete mb-2" />
                  <p className="font-semibold mb-1">IR Test</p>
                  <p className="text-sm text-muted-foreground">Compliant - ₹2,500</p>
                </div>
                <div className="bg-status-complete/10 p-4 rounded-lg border border-status-complete/20">
                  <CheckCircle2 className="w-6 h-6 text-status-complete mb-2" />
                  <p className="font-semibold mb-1">HV Test</p>
                  <p className="text-sm text-muted-foreground">Compliant - ₹4,000</p>
                </div>
              </div>
            </div>

            {/* Agent Summary */}
            <div className="bg-gradient-to-br from-primary/5 to-accent/5 p-6 rounded-lg border-2 border-primary/20">
              <h3 className="font-bold text-lg mb-4">Agent Processing Summary</h3>
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <CheckCircle2 className="w-5 h-5 text-status-complete" />
                  <div>
                    <p className="font-semibold">Sales Agent</p>
                    <p className="text-sm text-muted-foreground">
                      RFP detected and qualified successfully
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <CheckCircle2 className="w-5 h-5 text-status-complete" />
                  <div>
                    <p className="font-semibold">Technical Agent</p>
                    <p className="text-sm text-muted-foreground">
                      100% specification match achieved
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <CheckCircle2 className="w-5 h-5 text-status-complete" />
                  <div>
                    <p className="font-semibold">Pricing Agent</p>
                    <p className="text-sm text-muted-foreground">
                      Competitive pricing calculated
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <CheckCircle2 className="w-5 h-5 text-status-complete" />
                  <div>
                    <p className="font-semibold">Master Agent</p>
                    <p className="text-sm text-muted-foreground">
                      Final response generated and validated
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row justify-between items-center gap-4 animate-fade-in-up stagger-5">
          <Button variant="outline" size="lg" onClick={() => navigate("/")}>
            Back to Dashboard
          </Button>
          <div className="flex gap-4">
            <Button size="lg" variant="outline" onClick={handleDownloadPDF} className="gap-2">
              <Download className="w-5 h-5" />
              Download PDF Response
            </Button>
            <Button size="lg" onClick={handleSubmitResponse} className="gap-2">
              <Send className="w-5 h-5" />
              Submit RFP Response
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
